# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vivado/riscvcpu-vivado/riscvcpu-vivado.cache/wt [current_project]
set_property parent.project_path /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vivado/riscvcpu-vivado/riscvcpu-vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/jack/Documents/Git/riscvsoc/vivado/riscvcpu-vivado/riscvcpu-vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/headers/alu_definitions.vh
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/headers/control_definitions.vh
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/headers/general_definitions.vh
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/headers/immediate_generator.vh
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/headers/load_generator.vh
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/headers/store_generator.vh
}
read_mem {
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/first_test/instruction_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/shift_test/shift_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/load_store_test/load_store_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/lui_test/lui_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/auipc_test/auipc_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/branch_test/branch_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/jump_test/jump_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/factorial_test/factorial_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/factorial_test/factorial_test_compressed.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/csrrw_test/csrrw_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/mret_test/mret_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/asm/led_test/led_test.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vga/mem/vga_colour_palette.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vga/mem/text.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vga/mem/text_colour.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vga/mem/vga_font.mem
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/software/gcc/vga_test/vga_test.mem
}
read_verilog -library xil_defaultlib {
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/add.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/alu.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/branch_comparator.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/control.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/cpu.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/decode.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/immediate_generator.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/instruction_memory.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/led/led_wishbone.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/load_generator.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/mux2.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/mux3.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/mux_privilege.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/pc.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/privilege.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/ram/ram_wishbone.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/registers.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/cpu/store_generator.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vga/text_2_pixel.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vga/vga_generator.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/vga/vga_wishbone.v
  /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/board/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/board/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files /home/jack/Documents/Git/riscvsoc_sim/riscvsoc/board/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-3 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
